### ISSUE TITLE
CPU pegs when running demo code

### ISSUE THREAD

**Issue by tsunaminoai** [akarpovskii/tuile#11]
### Steps to reproduce and observed behavior
- Added tuile to a fresh zig project
- Used any example projects with tuile.run() for main.zig
- Built and ran using ReleaseSafe and Debug modes
- CPU runs to 100%

### Expected behavior
- Low to moderate CPU usage for main loop

### Environment
 - OS: x86_86-darwin
 - Zig: 0.12.0
 - Tuile: 0.1.2

### Additional context
If there are options to add delays to the main loop, they are not obvious from the provided documentation.

**Comment by akarpovskii** [comment]
Hi! The FPS is fixed to 30, but there were many unnecessary backend calls to enable/disable effects and change colors which effectively negated the delay between the frames.
Do you mind trying the version from #12?
```sh
zig fetch --save https://github.com/akarpovskii/tuile/archive/c15c44798568275e79edc0b0560c4922f54c8ba7.tar.gz
```

**Comment by tsunaminoai** [comment]
I've tried this on both x86_64-darwin and on aarch64-darwin and this CPU usage has dramatically reduced. Thank you!
